### ISSUE TITLE
Download Can't Be Locked Properly.

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#140] opened 2018-08-17 14:05 UTC
### Device Info
Device: ASUS PadFone S
Android Version: 6.0.1

### Logcat
```
I/ActivityManager(1802): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.providers.downloads.ui/.DownloadList bnds=[74,518][307,819]} from uid 10080 on display 0
I/ActivityManager(1802): Start proc 10044:android.process.media/u0a9 for activity com.android.providers.downloads.ui/.DownloadList
```

**Comment by acsway878787** [comment] 2018-08-19 08:37
Here's the full log:
```
I/ActivityManager(1815): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.providers.downloads.ui/.DownloadList bnds=[74,518][307,819]} from uid 10080 on display 0
W/System  (20764): ClassLoader referenced unknown path: /system/app/DownloadProviderUi/lib/arm
I/LoadedApk(20764): No resource references to update in package common
I/LoadedApk(20764): No resource references to update in package com.ngocgiap.xperia
I/LoadedApk(20764): No resource references to update in package com.ngocgiap.xperia
I/ActivityManager(1815): START u0 {act=android.provider.action.MANAGE_ROOT dat=content://com.android.providers.downloads.documents/root/downloads cmp=com.android.documentsui/.DocumentsActivity} from uid 10009 on display 0
I/ActivityManager(1815): Start proc 26563:com.android.documentsui/u0a33 for activity com.android.documentsui/.DocumentsActivity
W/System  (26563): ClassLoader referenced unknown path: /system/app/DocumentsUI/lib/arm
I/LoadedApk(26563): No resource references to update in package common
I/LoadedApk(26563): No resource references to update in package com.ngocgiap.xperia
I/LoadedApk(26563): No resource references to update in package com.ngocgiap.xperia
I/ActivityManager(1815): Start proc 26578:com.android.externalstorage/u0a10 for content provider com.android.externalstorage/.ExternalStorageProvider
W/System  (26578): ClassLoader referenced unknown path: /system/priv-app/ExternalStorageProvider/lib/arm
D/OpenGLRenderer(26563): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Documents(26563): update called before Search MenuItem installed.
I/LoadedApk(26578): No resource references to update in package common
I/LoadedApk(26578): No resource references to update in package com.ngocgiap.xperia
I/LoadedApk(26578): No resource references to update in package com.ngocgiap.xperia
D/ExternalStorage(26578): After updating volumes, found 2 active roots
I/Adreno-EGL(26563): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
I/Adreno-EGL(26563): OpenGL ES Shader Compiler Version: E031.29.00.00
I/Adreno-EGL(26563): Build Date: 12/04/15 Fri
I/Adreno-EGL(26563): Local Branch: mybranch17080070
I/Adreno-EGL(26563): Remote Branch: quic/LA.BF.1.1.3_rb1.5
I/Adreno-EGL(26563): Local Patches: NONE
I/Adreno-EGL(26563): Reconstruct Branch: NOTHING
I/OpenGLRenderer(26563): Initialized EGL, version 1.4
I/TouchPalIME(21195): TouchPalIME onFinishInput
I/TouchPalIME(21195): TouchPalIME onStartInput
I/ActivityManager(1815): Start proc 26598:com.android.shell/2000 for content provider com.android.shell/.BugreportStorageProvider
I/ActivityManager(1815): Displayed com.android.documentsui/.DocumentsActivity: +409ms (total +538ms)
W/System  (26598): ClassLoader referenced unknown path: /system/priv-app/Shell/lib/arm
D/Documents(26563): userMode=1, userSortOrder=0 --> mode=1, sortOrder=2
I/LoadedApk(26598): No resource references to update in package common
I/LoadedApk(26598): No resource references to update in package com.ngocgiap.xperia
I/LoadedApk(26598): No resource references to update in package com.ngocgiap.xperia
D/Documents(26563): Update found 8 roots in 368ms
D/Documents(26563): Update found 8 roots in 195ms
I/TouchPalIME(21195): TouchPalIME onFinishInput
I/TouchPalIME(21195): TouchPalIME onStartInput
I/UsageStatsService(1815): User[0] Flushing usage stats to disk
D/ConnectivityService(1815): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 126]
```

**Comment by acsway878787** [comment] 2018-08-31 02:29
@Maxr1998 Does this Logcat contain enough information to fix this issue?

**Comment by Maxr1998** [comment] 2019-01-17 15:57
Not really, though this will hopefully be fixed in a future implementation. Marking this as duplicate of #113 now.

**Closed by Maxr1998** 2019-01-17 15:57 UTC
