### ISSUE TITLE
Weird KitKat and below bootloop because of RemotePreferences

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#127] opened 2018-02-08 15:03 UTC
Phone: ASUS PadFone S
Android Version:4.4.2
Xposed version: 54

**Comment by Maxr1998** [comment] 2018-02-08 15:29
@acsway878787 Known issues. Working on it already in the last few weeks.

**Comment by Maxr1998** [comment] 2018-04-03 09:30
Nope, not yet. I just didn't get to identify the issue by now, and didn't want to push a potentially unstable version onto devices with KitKat, so every 7.X version is Android 5.0+. Hopefully I can fix this bug in the near future.

**Comment by Maxr1998** [comment] 2019-01-17 15:51
I couldn't ever reproduce this bug sadly, neither on my devices with KitKat nor the Emulator. It seems to be a vendor specific bug in the framework representation. However, next MaxLock release will drop KitKat support, as it's only used on a very small percentage of devices.
Thus, I'll be marking this as wontfix and closing this issue..

**Closed** 2019-01-17 15:52 UTC
Labels: bug, can't reproduce, won't fix
