### ISSUE TITLE
Can't Lock First Screen of Facebook

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#145] opened 2018-12-21 23:03 UTC
### Logcat
```
E/Xposed  (11758): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup X.0aX.K()' on a null object reference
E/Xposed  (11758): 	at com.facebook.katana.activity.FbMainTabActivity.startActivity(:175723)
E/Xposed  (11758): 	at de.Maxr1998.xposed.maxlock.hooks.Apps$1.beforeHookedMethod(Unknown Source)
E/Xposed  (11758): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
E/Xposed  (11758): 	at android.app.Activity.onStart(<Xposed>)
E/Xposed  (11758): 	at android.support.v4.app.FragmentActivity.onStart(:69030)
E/Xposed  (11758): 	at com.facebook.base.activity.FbFragmentActivity.onStart(:68941)
E/Xposed  (11758): 	at com.facebook.katana.activity.FbMainTabActivity.onStart(:68747)
E/Xposed  (11758): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
E/Xposed  (11758): 	at android.app.Activity.performStart(Activity.java:6701)
E/Xposed  (11758): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
E/Xposed  (11758): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
E/Xposed  (11758): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/Xposed  (11758): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
E/Xposed  (11758): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Xposed  (11758): 	at android.os.Looper.loop(Looper.java:154)
E/Xposed  (11758): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Xposed  (11758): 	at java.lang.reflect.Method.invoke(Native Method)
E/Xposed  (11758): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Xposed  (11758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Xposed  (11758): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

If there's more information needed, please tell me.

**Comment by Maxr1998** [comment] 2019-01-17 15:58
This looks like an incompatibility/a bug in Facebook's code - hopefully fixed in the next generation MaxLock implementation.

**Comment by Maxr1998** [comment] 2019-01-17 15:58
Duplicate of #113 btw.

**Closed** 2019-01-17 15:58 UTC
Labels: duplicate
