### ISSUE TITLE
Google Docs Can't Open Normally When Locked.

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#142] opened 2018-09-02 10:46 UTC
### Device Info
Device: ASUS PadFone S
Android Version: 6.0.1

### Problem Description
After I enter my password , the screen will jump back to the last screen before I opened Google Docs, but if I turn off MaxLock, it'll startup normally.

### Logcat When Locked On
```
I/ActivityManager(1835): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.apps.docs/.app.NewMainProxyActivity bnds=[74,518][307,819]} from uid 10080 on display 0
D/GmsDummySvc(3106): onBind: Intent { act=com.google.android.gms.phenotype.service.START flg=0x10 pkg=com.google.android.gms }
I/ActivityManager(1835): START u0 {flg=0x30000 cmp=de.Maxr1998.xposed.maxlock/.ui.LockActivity (has extras)} from uid 10193 on display 0
D/SafeParcel(3106): Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
D/GmsDummySvc(3106): bound by: GetServiceRequest{serviceId=PHENOTYPE, gmsVersion=12525000, packageName='com.google.android.apps.docs', extras=Bundle[{}]}
I/ActivityManager(1835): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.android.apps.docs/.app.legacy.NewMainProxyActivity bnds=[74,518][307,819]} from uid 10193 on display 0
D/ML-FPV  (2438): Starting authentication..
W/GAv4    (2438): Store full, deleting hits to make room, count: 1
D/GmsClearcutSvc(3106): onBind: Intent { act=com.google.android.gms.clearcut.service.START flg=0x10 pkg=com.google.android.gms }
D/SafeParcel(3106): Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
D/GmsClearcutSvc(3106): bound by: GetServiceRequest{serviceId=CLEARCUT_LOGGER, gmsVersion=12525000, packageName='com.google.android.apps.docs', extras=Bundle[{}]}
D/SafeParcel(3106): Unknown field num 0 in com.google.android.gms.playlog.internal.PlayLoggerContext, skipping.
D/GmsClearcutLogSvcImpl(3106): log: LogEventParcelable[1, PlayLoggerContext[1, package=com.google.android.apps.docs, packageVersionCode=183320230, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=true, logSourceName=DRIVE, isAnonymous=false, qosTier=0], LogEventBytes:, AddPhenotypeExperimentTokens: true]
D/SafeParcel(3106): Unknown field num 0 in com.google.android.gms.playlog.internal.PlayLoggerContext, skipping.
D/GmsClearcutLogSvcImpl(3106): log: LogEventParcelable[1, PlayLoggerContext[1, package=com.google.android.apps.docs, packageVersionCode=183320230, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=true, logSourceName=DRIVE, isAnonymous=false, qosTier=0], LogEventBytes:, AddPhenotypeExperimentTokens: true]
D/ML-FPV  (2438): Starting authentication..
D/SafeParcel(3106): Unknown field num 0 in com.google.android.gms.playlog.internal.PlayLoggerContext, skipping.
D/GmsClearcutLogSvcImpl(3106): log: LogEventParcelable[1, PlayLoggerContext[1, package=com.google.android.apps.docs, packageVersionCode=183320230, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=true, logSourceName=DRIVE, isAnonymous=false, qosTier=0], LogEventBytes:, AddPhenotypeExperimentTokens: true]
I/art     (1835): Background partial concurrent mark sweep GC freed 10771(779KB) AllocSpace objects, 4(84KB) LOS objects, 32% free, 33MB/49MB, paused 65.914ms total 152.745ms
I/ActivityManager(1835): START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10017 on display 0
```

### Logcat When Not Locked
```
I/ActivityManager(15602): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.apps.docs/.app.NewMainProxyActivity bnds=[74,518][307,819]} from uid 10080 on display 0
D/GmsDummySvc(16189): onBind: Intent { act=com.google.android.gms.phenotype.service.START flg=0x10 pkg=com.google.android.gms }
D/SafeParcel(16189): Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
D/GmsDummySvc(16189): bound by: GetServiceRequest{serviceId=PHENOTYPE, gmsVersion=12525000, packageName='com.google.android.apps.docs', extras=Bundle[{}]}
I/ActivityManager(15602): Displayed com.google.android.apps.docs/.app.NewMainProxyActivity: +124ms
I/ActivityManager(15602): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.android.apps.docs/.app.legacy.NewMainProxyActivity bnds=[74,518][307,819]} from uid 10193 on display 0
D/GmsClearcutSvc(16189): onBind: Intent { act=com.google.android.gms.clearcut.service.START flg=0x10 pkg=com.google.android.gms }
I/ActivityManager(15602): START u0 {flg=0x4000000 cmp=com.google.android.apps.docs/.doclist.activity.DocListActivity (has extras)} from uid 10193 on display 0
D/SafeParcel(16189): Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
D/GmsClearcutSvc(16189): bound by: GetServiceRequest{serviceId=CLEARCUT_LOGGER, gmsVersion=12525000, packageName='com.google.android.apps.docs', extras=Bundle[{}]}
```

**Comment by Maxr1998** [comment] 2019-01-17 16:03
Duplicate of #113.

**Closed by Maxr1998** 2019-01-17 16:03 UTC
