### ISSUE TITLE
[5.2] Stuck at Boot

### ISSUE THREAD

**Issue by gxgani** [Maxr1998/MaxLock#39] opened 2015-05-27 05:17 UTC
Device: Sony Xperia Z1 Compact
Android: Lollipop 5.0.2/(.270)

With 5.2 installed, device doesn't boot. Having look at dalvik-cache folder, I see the process being halt at maxlock's dex file. Clearing it doesn't help either.

**Comment by Maxr1998** [comment] 2015-05-27 07:31
Did you clear it multiple times? I had this issue too, but on time wipe doesn't help for me. Also, only clear dalvik, not normal cache..
Though it wonders me that you have the issue on 5.0.X...

**Comment by gxgani** [comment] 2015-05-27 08:40
I booted in by deleting maxlock apk. Reinstalled it, uninstalled(clearing data) and deleted the dalvik cache. Installed it again, strangely works but it keeps getting optimized at every boot.

Additionally, could I request you to add an option to lock apps upon screenlock? And also, may I know whats "pausing" as stated in 5.2 update.

**Comment by Maxr1998** [comment] 2015-05-27 08:45
That optimizing should only happen once, then it'll go away.
Screen off should already work.

Previously, apps got relocked when you cleared them from recents, now you always see lockscreen when you start them, even when they were open before.

**Comment by gxgani** [comment] 2015-05-27 11:54
This is disturbing. I had 2 apps(Whatsapp, QuickPick(Gallery Renamed)) protected with knock-code. I had everything removed(Input keys, lines, touch effect), rebooted and phone stuck again at boot.

Also I noticed, if you change settings from Lockscreen UI(such as Show lines, Input), they do not come into immediate effect for the apps under protection but MaxLock itself does.

**Comment by Maxr1998** [comment] 2015-05-27 13:03
Changing settings in ML shouldn't cause a bootloop. Did you update any other Xposed module?

That seems to be a bug of Android settings. I cannot tell you why this happens. Though I *could* force that update, that would significantly decrease performance..

**Comment by gxgani** [comment] 2015-05-27 13:11
I did update, it was the Serajr's Xperia Module. I am back to 5.1.1 which doesn't seem to produce that specific issue but has the slower performance which I didn't see in 5.2(Opening WhatsApp)

**Comment by Maxr1998** [comment] 2015-05-27 13:14
Yeah, as I said inb4, this is an Xposed bug which happens randomly on 5.X when updating any Xposed module, MaxLock 5.2 isn't the cause. Sometimes I get bootloop every morning at boot, sometimes it directly boots fine although I did an update..

**Comment by gxgani** [comment] 2015-05-27 13:18
Oh. The only bootloop issue I faced was when I had app packages more than 320(http://forum.xda-developers.com/crossdevice-dev/sony/workaround-bootloops-xposed-lollipop-t3089203). After that, I haven't come across any bootloops. And this specific issue, was a bootloop. But with 5.2, I am not facing boot loop, boot process get stuck at creating dex for maxlock.

**Comment by Maxr1998** [comment] 2015-05-27 13:43
Sorry, always when I say booloop I mean bootstuck. I only had bootstucks, which were all fixed by wiping dalvik. BTW, that seems to be an coincidence. I also had that bootstuck at dexing another module..

**Comment by gxgani** [comment] 2015-05-27 13:52
I got an exam to take tomorrow, will do a test with having only having installed maxlock and get back to this issue soon.

**Comment by Maxr1998** [comment] 2015-05-27 13:57
Ok, thank you. I'm on vacation from tomorrow to next Saturday (not this weeks one), but I will respond then.

**Comment by gxgani** [comment] 2015-05-27 13:58
Have a good one, you deserve it.

**Comment by gxgani** [comment] 2015-05-28 01:08
One Quick update, the bootstuck has to do with Maxlock's settings, since I was able to boot in when I cleared maxlock's appdata. I would like to know if you could reproduce this issue by enabling the following

Lock Mode: Knock Code
Lockscreen UI: Hide Input/Title Bar, Untick Show Dividers and Make touches visible
Apps: Whatsapp

**Comment by gxgani** [comment] 2015-05-28 01:20
Out of all the Lock modes, I can confirm that this issue is being caused by the new Knock Code design.

**Comment by Maxr1998** [comment] 2015-05-28 06:06
Hm, thanks for you observations..
That seems just so strange, it has nothing to do with the Xposed classes. I pretty exactly know when the fault started, and it seems the new IMoD is the issue. Could you try again without IMoD and with IMoD to see if it boots? I cannot do any tests, as I need my phone on my vacation and have no Computer for adb..

**Comment by gxgani** [comment] 2015-05-28 06:38
The previous observations had IMoD turned off, now I tried booting having IMoD turned on with default values and phone booted for the first time, second boot failed(cleared the dex), it booted the next time and the cycle repeated.

**Comment by Maxr1998** [comment] 2015-05-28 07:13
So it seems IMoD is definitely the issue? Then I finally know where to take a look at.. Thanks!

**Comment by Maxr1998** [comment] 2015-05-28 22:40
Reopened, as no fix is available by now..

**Comment by Maxr1998** [comment] 2015-06-07 19:30
My testing confirmed that it's definitely the two additional XSharedPreferences from IMod which cause this bug.

**Comment by Maxr1998** [comment] 2015-07-14 20:09
Fixed with 5.3

**Closed by Maxr1998** 2015-07-14 20:09 UTC
Labels: FINISHED/DONE
