### ISSUE TITLE
ForceClose while opening locked apps or open itself

### ISSUE THREAD

**Issue by runo280** [Maxr1998/MaxLock#133] opened 2018-03-29 06:04 UTC
Huawei Honor 5x
Latest nightly of Lineage OS 14.1
Xposed Framework 89
MaxLock v7.0.1

Sometimes I get FC on opening locked apps:
```
03-29 10:21:38.552 1403-1403/? I/SlideTouchEvent: vel=0.0, MinimumFlingVelocity=150
03-29 10:21:38.789 1060-1069/? I/art: Background partial concurrent mark sweep GC freed 48693(2MB) AllocSpace objects, 2(40KB) LOS objects, 33% free, 18MB/27MB, paused 2.911ms total 183.592ms
    
    --------- beginning of system
03-29 10:21:40.415 1060-2104/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.dv.adm.pay/.Main (has extras)} from uid 10027 on display 0
03-29 10:21:40.442 1060-1316/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=5550, uid=10027) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
    Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10027)
03-29 10:21:40.500 4527-4527/? I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-29 10:21:40.510 4527-4527/? I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-29 10:21:40.514 4527-4527/? I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-29 10:21:41.003 1060-2102/? I/ActivityManager: START u0 {flg=0x30000 cmp=de.Maxr1998.xposed.maxlock/.ui.LockActivity (has extras)} from uid 10094 on display 0
03-29 10:21:41.252 5395-5395/? I/AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
    java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at android.support.v7.app.j.b(Unknown Source)
        at android.support.v7.app.j.onCreateView(Unknown Source)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.view.LayoutInflater.inflate(<Xposed>)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at de.Maxr1998.xposed.maxlock.ui.a.c.<init>(Unknown Source)
        at de.Maxr1998.xposed.maxlock.ui.LockActivity.a(Unknown Source)
        at de.Maxr1998.xposed.maxlock.ui.LockActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatViewInflater" on path: DexPathList[[zip file "/data/app/de.Maxr1998.xposed.maxlock-1/base.apk"],nativeLibraryDirectories=[/data/app/de.Maxr1998.xposed.maxlock-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at java.lang.Class.forName(Class.java:326) 
        at android.support.v7.app.j.b(Unknown Source) 
        at android.support.v7.app.j.onCreateView(Unknown Source) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
        at android.view.LayoutInflater.inflate(<Xposed>) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at de.Maxr1998.xposed.maxlock.ui.a.c.<init>(Unknown Source) 
        at de.Maxr1998.xposed.maxlock.ui.LockActivity.a(Unknown Source) 
        at de.Maxr1998.xposed.maxlock.ui.LockActivity.onCreate(Unknown Source) 
        at android.app.Activity.performCreate(Activity.java:6684) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
```

Also while opening MaxLock:
```
03-29 10:29:12.831 6128-6128/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.Maxr1998.xposed.maxlock, PID: 6128
    java.lang.RuntimeException: Unable to destroy activity {de.Maxr1998.xposed.maxlock/de.Maxr1998.xposed.maxlock.Main}: java.lang.IllegalArgumentException: Service not registered: de.Maxr1998.xposed.maxlock.ui.SettingsActivity$1@a548aeb
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4240)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.IllegalArgumentException: Service not registered: de.Maxr1998.xposed.maxlock.ui.SettingsActivity$1@a548aeb
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1483)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
        at de.Maxr1998.xposed.maxlock.ui.SettingsActivity.onDestroy(Unknown Source)
        at android.app.Activity.performDestroy(Activity.java:6886)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4227)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258) 
        at android.app.ActivityThread.-wrap6(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
```

**Comment by Maxr1998** [comment] 2018-03-29 19:22
Which Browser do you have installed? Chrome? Firefox? Both?
Does the first report actually crash the app? It doesn't look like that Exception should cause a crash..

**Comment by Maxr1998** [comment] 2018-03-29 20:29
Ok, fixed the second bug. Seems to occur only when there's no Custom Tab supporting browser installed.

**Comment by Maxr1998** [comment] 2018-04-04 20:02
Can't reproduce the first issue, thus closing this now.

**Closed** 2018-04-04 20:02 UTC
Labels: bug, can't reproduce
